name: 🚀 Deploy PAI-NAI to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Test Backend
      run: |
        cd backend
        npm ci
        npm run build
        # npm test  # Uncomment when tests are ready
    
    - name: Test Frontend
      run: |
        cd frontend
        npm ci
        npm run build
        npm run lint

  # Manual deployment instructions
  # Railway and Vercel will auto-deploy from GitHub
  # No need for complex GitHub Actions for free tier 